# Generated by Django 2.2.4 on 2019-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.CharField(default='0,0,0', max_length=10000),
        ),
    ]
