# Generated by Django 2.2.4 on 2019-08-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_player_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='total_score',
        ),
    ]
