# Generated by Django 2.2.4 on 2019-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_player_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
